### PR TITLE
Move to traditional android gradle project layout

### PR DESCRIPTION
**Pull request by gsantner**
* Moved project to the traditional structure of android studio/gradle  android projects
* Updated gitignore and removed ignored files that still were checked in
* Everything else (code) stays the same

Don't get frightened by so much changes. They are mostly movements.

Tried it on both, Android Studio, and gradle command line, assembles without any problems.
grafik

This is the first step to cleanup the project :)  
If you merge, I'm gonna make another PR, which will do most common cleanup things of code. E.g. organizing imports, fixing common whitespace issues, reordering XML accordingly, ...
Afterwards the project will be in a state, so other devs can easier contribute to your project.

### CODE REVIEW

**Comment by BennyKok** [comment]
hey man would you mind updating some of the files and repull the request

**Comment by BennyKok** [comment]
and do you want to be a part of the collaborator, to commit the code directly

**Comment by BennyKok** [comment]
ok now, manual merged

**Comment by gsantner** [comment]
yes, you can add me to collaborators

**Comment by gsantner** [comment]
yes, you can add me to collaborators/maintainers of the app

@BennyKok  @scoute-dich  @dkanada 
Please do a fresh clone now, before developing new stuff. To avoid a lot of merge conflicts/pushing bad stuff again into repo.

See: 
* <https://github.com/BennyKok/OpenLauncher/commit/8fb7a5a465d6d26d02beb918e9d3c8a9f1a65308>
* #28

**Pull request merged**
