### PR TITLE
strings, hide launcher icon, tap to open app drawer

### PR DESCRIPTION
**Pull request by scoute-dich**
So, it was a little confusing, because you made commits, during I worked on some changes... But it seems, that my commits are now able to be merged.

My changes:
- Since swipe to open app drawer doesn't work very properly, I added tap on desktop to open app drawer.
- I also added an option to hide the launcher icon. For that reason it was necessary to add the Activity_start. Otherwise the launcher wouldn't open anymore after disabling the icon.
- I think I put most hardcoded strings in resources and translated in German. Other languages could now also be added without problems.

Again: thanks for your hard work. I really love the launcher.

Regards
Gaukler Faun

### CODE REVIEW

**Comment by BennyKok** [comment]
I am sorry the change I did cause conflict to the things you changed, as I immediately saw the problem of swipe to open the drawer in you previous commit, you just need to return true in the listener. But what I changed is to put the code in the on touch listener and use custom way to read the swipe up action.

The latest commit I did is to split the (swipe/click) to open app drawer (and some wording fix in the eng translation ), later I will put a picker over there to let user to choose instead of two boolean. I renamed the Activity_start to Activity_init. May I know why you add a new activity to start the Home, are you planning to add something like introduction there or something else.

Please update before you make any further changes, I don't want any conflicts to happen to you!

**Comment by scoute-dich** [comment]
I added the Activity_init because when we hide the launcher, we remove the app from the system installed application list. So the system can't launch the app anymore. So we can hide the Activity_init but the system can still launch the launcher when pressing "home", because we left the "android.intent.category.HOME" and the other intents in the Home activity.

But yes, perhaps we can use it to show a short introduction activity. I just used  https://github.com/chyrta/AndroidOnboarder to build such an activity in an other app today...

BTW, thanks for the invitation.

**Comment by TeamBrainStorm** [comment]
I noticed that and I totally agree with why you did that!

Great job!

**Comment by TeamBrainStorm** [comment]
One other thing I'd like to mention is that in all apps mode when you
uninstall a app the icon stays on the home screen until you go to move it
just wanted to let you guys know :)

**Comment by scoute-dich** [comment]
Just created the intro screens ;-)

**Comment by TeamBrainStorm** [comment]
Looks amazing! Great job!

**Pull request merged**
