### PR TITLE
Purge unnecesary tracked files.

### PR DESCRIPTION
**Pull request by mastrgamr**
Lighten the repo a bit by removing automatically generated files created by Android Studio.
Specifically /gradle, any /build, and /.idea directories.

These files will automatically get generated on the PC when a contributor pulls the repo.

### CODE REVIEW

**Comment by BennyKok** [comment]
I didnt saw your pull request when I push the commit, and now it wont let me merge the pull request due to some file conflicts, I am not sure what is happening right now.

**Comment by mastrgamr** [comment]
This Pull Request did not have any conflicts when I made it. So it must mean you probably made changes locally and pushed to the repo. Those changes now conflict with this Pull Request.

I might have to pull your new changes to my machine and redo the Pull Request.

**Comment by BennyKok** [comment]
I am confused, but it let me commit now.

**Comment by mastrgamr** [comment]
@BennyKok All good now. Merge merge merge! 👍

**Comment by BennyKok** [comment]
Thank you very much.

**Pull request merged**
